# Change these first
owner: sladerx4 # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Interface
    url: http://interfacenet.com.ar/
  - name: Ctear
    url: http://ctear.com.ar/
  - name: CobroDigital
    url: https://cobrodigital.com/
  - name: Facebook
    url: https://www.facebook.com/
  - name: Google
    url: https://www.google.com
  - name: Instagram
    url: https://www.instagram.com/
  - name: Steam
    url: https://store.steampowered.com/

assignees:
  - sladerx4

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: sladerx Upptime
  introTitle: "**Upptime** servicio de monitoreo de estado y uptime de paginas "
  introMessage: Monitoreo del estado de paginas propias y de paginas de importancia
  navbar:
    - title: Estado
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
